export const locale = {
    dashboard_origin: 'لوحة التحكم',
    menu: 'قائمة',
    get_menu_again: 'احصل على القائمة مرة أخرى',
    loading_error: {
        title: 'خطأ في التحميل!',
        message: 'فشل تحميل البيانات! الرجاء المحاولة مرة أخرى',
        text: 'أعد المحاولة'
    },
    copy_right: {
        year: '١٤٠٤',
        text1: 'جميع الحقوق المادية والمعنوية لهذا النظام محفوظة ومملوكة لشركة الدعاية والإعلان',
        text2: 'رواد الأعمال المتميزون',
        text3: 'سبهر آراد، وأي نسخ أو تقليد سيؤدي إلى ملاحقة قانونية.'
    },
    user: 'المستخدم العزيز',
    hi: 'مرحباً',
    exit: 'خروج',
    go_to_page: 'اذهب إلى الصفحة',
    show: "عرض",
    until: "حتى",
    from: "من",
    page: 'صفحة',
    notes: 'الملاحظات',
    created_at: 'تاريخ الإنشاء',
    registration: 'تسجيل',
    edit_contact: 'تعديل جهة الاتصال',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    contact_info: 'معلومات الاتصال',
    add_birthday: 'إضافة تاريخ الميلاد',
    contacts: 'دفاتر جهات الاتصال',
    last_updated_at: 'آخر تحديث',
    added_to_contact: 'أضيفت إلى جهات الاتصال',
    contact_registered: "لم يتم حفظ جهة الاتصال الخاصة بك.",
    transaction: 'العملية',
    write_message: 'اكتب رسالة',
    note_title: 'عنوان الملاحظة',
    create_note: 'إضافة ملاحظة',
    are_you_sure_to_delete: 'هل أنت متأكد من الحذف؟',
    last_transaction: 'آخر العمليات',
    your_balance: 'رصيدك',
    no_transaction: 'لم يتم تسجيل أي عملية لك بعد!',
    increase_balance: 'زيادة الرصيد',
    transaction_list: 'قائمة العمليات',
    withdraw: 'سحب النقود',
    decrease: 'سحب النقود',
    deposit: 'إيداع النقود',
    increase: 'إيداع النقود',
    charge: 'شحن المحفظة',
    refund: 'استرجاع النقود',
    save: 'حفظ',
    reload: 'إعادة تحميل القائمة',
    shared: 'مشترك',
    list: 'قائمة',
    single_add: 'إضافة فردية',
    mass_add: 'إضافة جماعية',
    excel_add: 'إضافة من ملف Excel',
    added_successfully: 'تمت الإضافة بنجاح',
    error_add_phone: 'خطأ في إضافة الرقم',
    group: {
        add: 'إضافة مجموعة جديدة',
        delete: 'حذف مجموعة',
        edit: 'تعديل مجموعة',
        first: 'الرجاء إضافة مجموعة جديدة أولاً.'
    },
    successfully_deleted: "تم الحذف بنجاح",
    notification: {
        text: 'إشعارات المستخدم',
        new: 'رسالة جديدة',
        messages: 'الرسائل',
        events: 'الأحداث',
        no_new_message: 'لا توجد رسائل جديدة!',
        show_all: 'عرض الكل',
        no_new_event: 'لا توجد أحداث جديدة!',
        go_to_user: 'اذهب إلى المستخدم',
        watched: 'شاهدت'
    },
    locking_for_service: 'ما هي الخدمة التي تبحث عنها؟',
    service_name: 'أدخل اسم الخدمة التي تريدها...',
    invite: {
        title: 'قدم النظام لأصدقائك.',
        gift: 'هدية',
        get: 'احصل عليها.',
        phone: 'أدخل الرقم.',
        invite: 'ادعُ!',
        got_it: 'فهمت',
        get_gift: 'احصل على الهدية',
        success: 'تم إرسال رسالة دعوتك بنجاح.',
        wrong_number: 'الرجاء إدخال رقم صحيح.',
    },
    ticker: {
        text: 'نحن معك في كل لحظة...',
        help: 'للتواصل مع فريق الدعم الفني لدينا، قم بتقديم تذكرة',
        register: 'تسجيل تذكرة'
    },
    package: {
        title: 'الباقات النشطة',
        no: 'ليس لديك أي باقة نشطة.',
        no_limit: 'لوحة غير محدودة',
        day: ' يوم',
        other: ' آخر',
        expiration: 'انتهاء الصلاحية',
        expired: 'منتهية الصلاحية',
    },
    Loading: {
        Waiting: "الرجاء الانتظار",
        Description: "انتظر لحظة"
    },
    Questions: {
        Yes: "نعم",
        No: "لا"
    },
    Success: {
        Title: "نجاح",
        defaultActionText: "فهمت"
    },
    Info: {
        Title: "إشعار",
        defaultActionText: "فهمت"
    },
    Warning: {
        Title: "تنبيه",
        defaultActionText: "فهمت"
    },
    Error: {
        Title: "خطأ",
        defaultActionText: "فهمت"
    },
    Wallet: {
        Title: "رصيد غير كافٍ",
        defaultActionText: "فهمت"
    },
    ConnectionLost: {
        Title: "تم قطع اتصالك بالإنترنت",
        Subtitle: "الرجاء التأكد من اتصالك بالإنترنت",
        Button: "أعد المحاولة"
    },
    emoji: "إيموجي",
    text_suggest_free: "مستشار النصوص (مجاني)",
    select_campaign: "اختيار الحملة",
    short_link: "رابط قصير",
    text_suggest: "مستشار النصوص",
    select_emoji: "اختيار إيموجي",
    default_text: "نص افتراضي",
    emoji_group: {
        "Smileys & Emotion": "الوجوه التعبيرية والعواطف",
        "People & Body": "الأشخاص والجسم",
        "Animals & Nature": "الحيوانات والطبيعة",
        "Food & Drink": "الطعام والشراب",
        "Travel & Places": "السفر والأماكن",
        "Activities": "الأنشطة",
        "Objects": "الأشياء",
        "Symbols": "الرموز",
        "Flags": "الأعلام"
    },
    "table": {
        "index": "الرقم",
        "title": "العنوان",
        "text": "النص",
        "select": "اختيار",
        "next": "التالي",
        "previous": "السابق",
        "rows_per_page": "العدد في الصفحة",
        "no_data": "لا توجد بيانات للعرض",
        "search_placeholder": "بحث"
    },
    "modal": {
        "success": "نجاح"
    },
    "actions": {
        "remove": "حذف",
        "copyLink": "نسخ الرابط",
        operations: "العمليات",
        edit: "تعديل",
        delete: "حذف",
        show: "عرض",
        accept: "قبول",
        reject: "رفض",
        enable: "تفعيل",
        download: "تنزيل",
        deactive: "تعطيل"
    },
    "general": {
        "row": "صف",
        "id": "المعرّف",
        "back": "عودة",
        "manage": "إدارة",
        SENDING: "قيد الإرسال"
    },
    "shortLink": {
        "freeShorten": "قم بتقصير روابطك \"مجاناً\".",
        "clickToSelect": "اضغط على الرابط الذي تريده للاختيار.",
        "create": "إنشاء رابط قصير",
        "title": "العنوان",
        "titleHint": "الرجاء إضافة اسم للرابط القصير الخاص بك.",
        "link": "الرابط",
        "linkHint": "أدخل الرابط الذي تريده.",
        "shortenedLink": "الرابط القصير",
        "clickCount": "عدد النقرات",
        "selectDomain": "اختيار النطاق"
    },
    "pagination": {
        "next": "التالي",
        "previous": "السابق",
        "rowsPerPage": "العدد في الصفحة",
        "noData": "لا توجد بيانات للعرض",
        "search": "بحث"
    },
    "validation": {
        "titleRequired": "العنوان مطلوب",
        "minLength4": "يسمح بـ 4 أحرف على الأقل",
        "linkRequired": "الرابط مطلوب",
        "mustIncludeHttps": "يجب أن يتضمن https://",
        "invalidLink": "الرجاء إدخال رابط صحيح."
    },
    "messages": {
        "addedSuccessfully": "تمت الإضافة بنجاح.",
        "confirmDeleteShortLink": "تأكيد حذف الرابط القصير؟"
    },
    "inputMenu": {
        "text": "النص",
        "selectUserInfo": "اختيار معلومات المستخدم"
    },
    "patternDialog": {
        "title": "اختيار قالب/حملة",
        "change": "تغيير القالب/الحملة",
        "createPattern": "تسجيل قالب جديد",
        "createCampaign": "تسجيل حملة جديدة",
        "tabs": {
            "pattern": "اختيار قالب",
            "campaign": "اختيار حملة"
        },
        "empty": "لم يتم العثور على أي قالب، الرجاء تسجيل قالب أولاً.",
        "columns": {
            "id": "المعرّف",
            "type": "النوع",
            "pattern": "القالب",
            "static": "ثابت",
            "title": "العنوان",
            "content": "النص",
            "status": "الحالة",
            "rejected": "مرفوض",
            "approved": "مقبول"
        },
        "pagination": {
            "next": "التالي",
            "prev": "السابق",
            "rowsPerPage": "العدد في الصفحة",
            "noData": "لا توجد بيانات للعرض",
            "search": "بحث"
        }
    },
    "PATTERN": {
        "SELECTED_MESSAGE": "الرسالة المختارة:",
        "REQUIRED_INPUTS": "المدخلات المطلوبة:",
        "SELECTED_CAMPAIGN": "الحملة المختارة:",
        "CAMPAIGN_ID": "المعرّف",
        "PRE_NAME": "اللقب",
        "NAME": "الاسم",
        "MIDDLE_NAME": "الاسم الأوسط",
        "LAST_NAME": "اسم العائلة",
        "POST_NAME": "اللاحقة",
        "ALIAS": "الاسم المستعار",
        "COMPANY": "الشركة",
        "JOB_TITLE": "المسمى الوظيفي",
        "PHONE": "رقم الهاتف",
        "BIRTHDAY": "تاريخ الميلاد",
        "DESCRIPTION": "الوصف"
    },
    "CONTACT_GROUP": {
        "LIST": "قائمة",
        "ADD": "إضافة",
        "SEARCH": "بحث",
        "INDEX": "الرقم",
        "ID": "المعرّف",
        "GROUP_NAME": "اسم المجموعة",
        "PARENT": "الوالد",
        "CREATE": {
            "GROUP_NAME": "اسم المجموعة الافتراضي",
            "PARENT_CATEGORY": "الفئة الوالدة",
            "ADD_GROUP": "إضافة مجموعة",
            "SUCCESS": "تمت إضافة المجموعة الافتراضية بنجاح.",
            "ERROR": "خطأ في إضافة المجموعة الافتراضية!",
            "SEARCH": "بحث",
            "TITLE": "العنوان",
            "SEARCH_IN_TITLE": "بحث في العنوان",
            "FROM": "من",
            "TO": "إلى",
            "BIRTHDAY_FROM": "تاريخ الميلاد من",
            "BIRTHDAY_TO": "إلى تاريخ",
            "ITEMS_PER_PAGE": "العدد في الصفحة",
            "PHONE_COPY": "نسخ الرقم",
            "COPY_PHONE": "نسخ الرقم",
            "DELETE_CONTACT_GROUP": "حذف جهة الاتصال من المجموعة",
            "DELETE_FROM_GROUP_ONLY": "حذف جهة الاتصال من هذه المجموعة فقط",
            "DELETE_FROM_ALL_GROUPS": "حذف جهة الاتصال من جميع المجموعات",
            "USER": "المستخدم",
            "PHOTO": "صورة",
            "FULL_NAME": "الاسم الكامل",
            "EMAIL": "البريد الإلكتروني",
            "PHONE_NUMBER": "رقم الهاتف المحمول",
            "JOB_TITLE_COMPANY": "المسمى الوظيفي والشركة",
            "CREATED_AT": "وقت الإنشاء",
            "PHONEBOOK": "دفتر الهاتف",
            "ACTIONS": "العمليات"
        },
        "TITLE": "العنوان",
        "SEARCH_IN_TITLE": "بحث في العنوان",
        "FROM": "من",
        "TO": "إلى",
        "BIRTHDAY_FROM": "تاريخ الميلاد من",
        "BIRTHDAY_TO": "إلى تاريخ",
        "ITEMS_PER_PAGE": "العدد في الصفحة",
        "PHONE_COPY": "نسخ الرقم",
        "COPY_PHONE": "نسخ الرقم",
        "DELETE_CONTACT_GROUP": "حذف جهة الاتصال من المجموعة",
        "DELETE_FROM_GROUP_ONLY": "حذف جهة الاتصال من هذه المجموعة فقط",
        "DELETE_FROM_ALL_GROUPS": "حذف جهة الاتصال من جميع المجموعات",
        "USER": "المستخدم",
        "PHOTO": "صورة",
        "FULL_NAME": "الاسم الكامل",
        "EMAIL": "البريد الإلكتروني",
        "PHONE_NUMBER": "رقم الهاتف المحمول",
        "JOB_TITLE_COMPANY": "المسمى الوظيفي والشركة",
        "CREATED_AT": "وقت الإنشاء",
        "PHONEBOOK": "دفتر الهاتف",
        "ACTIONS": "العمليات"
    },
    "GRADUAL": {
        "SEND_GRADUAL": "الإرسال التدريجي",
        "ALLOWED_HINT": "للإرسال بأعداد أكبر من ٥٠٠ رقم",
        "SEND_GRADUAL_OPTION": "الإرسال بشكل تدريجي",
        "AFTER_EVERY": "بعد كل",
        "SEND_SMS": "رسالة نصية قصيرة يجب أن ترسل؟",
        "TIME_INTERVAL": "الفاصل الزمني",
        "SMS_PART": "عدد الرسائل النصية القصيرة",
        "SMS_PART_HINT": "أدخل عدد الرسائل النصية القصيرة في كل جزء من الإرسال.",
        "COUNT_ERROR": "عدد الرسائل النصية القصيرة في كل جزء لا يمكن أن يكون أقل من ٥٠٠!"
    },
    "HISTORY": {
        "CREATE_NEW": "إنشاء تاريخ جديد",
        "BACK": "عودة",
        "TITLE": "عنوان التاريخ",
        "STEP": "الخطوة",
        "LAST_CALL": "وقت آخر مكالمة",
        "DISCUSSIONS": "المناقشات التي تمت",
        "REMIND_DATE": "وقت التذكير",
        "FOLLOWUP": "البنود للمتابعة في المكالمة التالية",
        "SAVE_HISTORY": "حفظ التاريخ",
        "INDEX": "الرقم",
        "SAVED_BY": "المسجّل بواسطة",
        "ACTION": "إدارة",
        "MORE_INFO": "مزيد من المعلومات حول",
        "CREATE_ERROR": "خطأ في إضافة تاريخ العميل!"
    },
    "FORMS": {
        "SourceNumber": "الرقم المصدر",
        "DestinationPhone": "الرقم الوجهة",
        "Add": "إضافة",
        "SEND_TO_SELECTED_NUMBERS": "إرسال إلى الأرقام المختارة",
        "CHANGE_PATTERN_CAMPAIGN": "تغيير القالب/الحملة",
        "SendTime": "وقت الإرسال",
        "SELECTED_MESSAGE": "الرسالة المختارة",
        "REQUIRED_INPUTS": "المدخلات المطلوبة",
        "SELECTED": "مختار",
        "ID": "المعرّف",
        "SEND": "إرسال",
        DATE_REQUIRED: "اختيار التاريخ إلزامي.",
        TIME_INTERVAL: "الفاصل الزمني",
        TIME_INTERVAL_FROM_PREVIOUS: "الفاصل الزمني من الرسالة السابقة",
        Title: "العنوان",
        LINK: "الرابط",
        LINK_HINT: "أي",
        LINK_PLACEHOLDER: "مثال: (https://example.ex/any)",
        LINK_SHORTENED_HINT: "سيتم استبدال رابطك بعد تقصيره بطول 14 حرفًا (example.ex/any) في النص، وسيتم إرسال رابط مخصص لكل رسالة.",
        Text: "النص",
        MUST_INCLUDE_PATTERN: "يجب أن يتضمن {pattern}",
        INVALID_LINK: "الرجاء إدخال رابط صحيح"
    },
    "ERRORS": {
        "PhoneIsNotValid": "رقم الهاتف غير صالح",
        "MaxPhoneLimit": "لا يمكنك إضافة أكثر من 50000 رقم.",
        "NoSelectedLineNumber": "لم يتم اختيار رقم مصدر.",
        INVALID_TIMER: "الرجاء إدخال وقت صحيح"
    },
    "NOTICES": {
        "Attention": "تنبيه",
        "MinimumSendWarning": "عند إرسال رسالة نصية قصيرة برقم مصدر \"إرسال إخباري\"، يجب أن يكون الحد الأدنى للعدد هو {{number}}."
    },
    "contactsTags": {
        "select_group": "اختيار مجموعة",
        "create_group": "إنشاء مجموعة",
        "search": "بحث",
        "add_group": "إضافة مجموعة",
        "enter_group_name": "أدخل الاسم الذي تريده",
        "group_name": "اسم المجموعة",
        "cancel": "إلغاء",
        "edit": "تعديل",
        "save": "حفظ",
        "loading_categories": "جاري تحميل الفئات...",
        "select_group_and_subgroup": "اختيار المجموعة والمجموعة الفرعية",
        "add_group_with_subgroups": "إضافة المجموعة مع المجموعات الفرعية",
        "add_group_only": "إضافة المجموعة المختارة فقط",
        "duplicate_name_error": "الاسم مكرر",
        "added_successfully": "تمت الإضافة بنجاح.",
        "confirm_delete_group": "تأكيد حذف المجموعة؟",
        "deleted_successfully": "تم الحذف بنجاح",
        "edited_successfully": "تم التعديل بنجاح",
        "group_added_successfully": "تمت إضافة المجموعات المختارة بنجاح.",
        "error_creating_group": "خطأ في إنشاء المجموعة الافتراضية",
        "create_default_group": "إنشاء مجموعة افتراضية",
        "select_default_group": "اختيار مجموعة افتراضية",
        "add_custom_group": "إضافة مجموعة باسم مخصص"
    },
    "CONTACT_SHARE": {
        "ADD_PHONE_NUMBER": "إضافة رقم هاتف",
        "ADD": "إضافة",
        "SHARE_ACCESS": "باختيار أي من الخيارات التالية، قم بمشاركة الوصول المطلوب مع الآخرين.",
        "SELECT_ACCESS": "اختيار الوصول لدفتر الهاتف",
        "DELETE": "حذف",
        "EDIT": "تعديل",
        "SEND": "إرسال",
        "PERSONS_WITH_ACCESS": "الأشخاص الذين لديهم وصول",
        "REMOVE_ACCESS": "إزالة الوصول",
        "RETURN": "عودة",
        "SAVE_CHANGES": "حفظ التغييرات",
        "SHARE_CONTACT_BOOK": "مشاركة دفتر الهاتف",
        "PHONE_VALIDATION": "الرجاء إدخال رقم هاتف صحيح",
        "SUCCESS_SHARE": "تمت مشاركة دفتر الهاتف بنجاح.",
        "ERROR_SHARE": "خطأ في مشاركة دفتر الهاتف!",
        "PHONE_DUPLICATE": "الرقم موجود مسبقاً!",
        "CHANGES_SAVED": "تم حفظ التغييرات بنجاح.",
        "ERROR_SAVING_CHANGES": "خطأ في حفظ التغييرات!"
    },
    "CONTACT_SEARCH": {
        "SEARCH": "بحث",
        "ADD_NUMBER": "أضف رقمًا"
    },
    "BUTTONS": {
        "DELETE_NUMBERS": "حذف الأرقام",
        "ADD_BULK": "إضافة جماعية",
        "FROM_FILE": "من ملف"
    },
    "CONTACT_PAGINATION": {
        "PER_PAGE": "العدد في كل صفحة",
        "FROM": "من",
        "TO": "إلى",
        "TOTAL": "العدد الكلي"
    },
    "SUCCESS": {
        "DELETED": "تم الحذف بنجاح",
        "SUCCESS": "نجاح"
    },
    "CONFIRM": {
        "DELETE_BULK": "حذف الأرقام غير المحفوظة؟"
    },
    "TOOLTIP": {
        "CopyPhoneNumbers": "انسخ أرقامك ثم اضغط",
        "COPY_LINK": "نسخ الرابط",
        "COPY_NUMBER": "نسخ الرقم",
        "SEE_PROFILE": "مشاهدة الملف الشخصي"
    },
    "CONTACT_EDIT": {
        "EDIT": "تعديل",
        "DELETE": "حذف"
    },
    "CONTACT_MENU": {
        "SHARE": "مشاركة",
        "PRINT": "طباعة",
        "EXCEL_EXPORT": "تصدير إلى Excel",
        "DELETE": "حذف",
        "SUCCESS_DELETE": "تم الحذف بنجاح.",
        "ERROR_DELETE": "خطأ في حذف جهات الاتصال!"
    },
    "CONTACTS": {
        PREFIX: "اللقب",
        NAME: "الاسم",
        MIDDLENAME: "الاسم الأوسط",
        LASTNAME: "اسم العائلة",
        POSTFIX: "اللاحقة",
        ALIAS: "الاسم المستعار",
        COMPANY: "الشركة",
        JOBTITLE: "المسمى الوظيفي",
        PHONE: "رقم الهاتف",
        PHONE_PLACEHOLDER: "مثال: 8070 111 13 (989)(989+)(9)(09)",
        ADD_EMAIL: "إضافة بريد إلكتروني",
        EMAIL: "البريد الإلكتروني",
        ADD_ADDRESS: "إضافة عنوان",
        ADDRESS: "العنوان",
        PROVINCE: "المحافظة",
        CITY: "المدينة",
        POSTALCODE: "الرمز البريدي",
        YEAR_OPTIONAL: "السنة (اختياري)",
        MONTH: "الشهر",
        DAY: "اليوم",
        ADD_BIRTHDAY: "إضافة تاريخ الميلاد",
        ADD_WEBSITE: "إضافة موقع ويب",
        WEBSITE: "موقع الويب",
        ADD_DATE: "إضافة تاريخ",
        DATE: "التاريخ",
        CUSTOM_FIELD: "حقل مخصص",
        ADD_CUSTOM_FIELD: "إضافة حقل مخصص",
        NOTE: "ملاحظة",
        ADD_NOTE: "إضافة ملاحظة",
        HOME: "المنزل",
        WORK: "العمل",
        OTHER: "أخرى",
        PROFILE: "الملف الشخصي",
        BLOG: "المدونة",
        HOMEPAGE: "الصفحة الرئيسية",
        TITLE: "العنوان",
        BIRTHDAY_ERROR: "الرجاء إدخال تاريخ صحيح",
        YEAR_ERROR: "٤ أرقام",
        EMAIL_ERROR: "الرجاء إدخال بريد إلكتروني صحيح",
        WEBSITE_ERROR: "الرجاء إدخال رابط صحيح (website.com)",
        PHONE_ERROR: "الرجاء إدخال رقم هاتف صحيح",
        ADD_HISTORY: "إضافة تاريخ",
        HISTORY_LIST: "قائمة التواريخ",
        EDIT_CONTACT: "تعديل جهة الاتصال",
        SHOW_CONTACT: "عرض جهة الاتصال"
    },
    "MONTHS": {
        "FARVARDIN": "يناير",
        "ORDIBEHESHT": "فبراير",
        "KHORDAD": "مارس",
        "TIR": "أبريل",
        "MORDAD": "مايو",
        "SHAHRIVAR": "يونيو",
        "MEHR": "يوليو",
        "ABAN": "أغسطس",
        "AZAR": "سبتمبر",
        "DEY": "أكتوبر",
        "BAHMAN": "نوفمبر",
        "ESFAND": "ديسمبر"
    },
    "GENERAL": {
        "PRINT": "طباعة",
        "DELETE": "حذف",
        "SUBMIT": "إرسال",
        "SUCCESSFULLY_ADDED": "تمت الإضافة بنجاح"
    },
    "UPLOAD_EXCEL": {
        "DOWNLOAD_SAMPLE": "تنزيل واستخدام نموذج ملف Excel",
        "UPLOAD_TITLE": "رفع الملف",
        "DRAG_DROP_TEXT_PART1": "اسحب وأفلت للرفع أو",
        "DRAG_DROP_TEXT_PART2": "هنا",
        "DRAG_DROP_TEXT_PART3": "اضغط",
        "FILE_INPUT_LABEL": "تحميل ملف Excel"
    },
    "SUCCESS_MESSAGE": {
        "LINK_COPIED": "تم نسخ الرابط بنجاح!"
    },
    "ERROR_MESSAGE": {
        "COPY_LINK_FAILED": "خطأ في نسخ الرابط."
    },
    "POPUP": {
        "TITLE_OR_BUTTON_TEXT": "اختيار قالب/حملة",
        "BUTTON_EDIT_TEXT": "تغيير قالب/حملة"
    },
    "BUTTON": {
        "REGISTER_NEW_PATTERN": "تسجيل قالب جديد",
        "REGISTER_NEW_CAMPAIGN": "تسجيل حملة جديدة",
        "CREATE_NEW_HISTORY": "إنشاء تاريخ جديد",
        "SAVE_HISTORY": "حفظ التاريخ",
        "SELECT_GROUP": "اختيار مجموعة",
        "CREATE_GROUP": "إنشاء مجموعة",
        "ADD_GROUP": "إضافة مجموعة",
        "SAVE": "حفظ",
        "CREATE_GROUP_SINGULAR": "إنشاء مجموعة",
        "ADD": "إضافة",
        "SEND": "إرسال",
        "EDIT_PERMISSIONS": "تعديل",
        "GO_BACK": "عودة",
        "SAVE_CHANGES": "حفظ التغييرات",
        GUIDE: "دليل",
        START: "ابدأ",
        EDIT: "تعديل",
        CANCEL: "إلغاء",
        AUTO_REFRESH: "تحديث تلقائي",
        AUTO_REFRESH_SETTINGS: "إعداد التحديث التلقائي",
        BACK: "عودة"
    },
    "TABS": {
        "SELECT_PATTERN": "اختيار قالب",
        "SELECT_CAMPAIGN": "اختيار حملة",
        "LIST": "قائمة",
        "ADD": "إضافة",
        "ADD_CUSTOM_GROUP": "إضافة مجموعة باسم مخصص",
        "SELECT_DEFAULT_GROUP": "اختيار مجموعة افتراضية"
    },
    "NO_DATA": {
        "NO_PATTERN": "لم يتم العثور على أي قالب، الرجاء تسجيل قالب أولاً."
    },
    "TABLE": {
        "ID": "المعرّف",
        "TYPE": "النوع",
        "PATTERN": "القالب",
        "STATIC": "ثابت",
        "TITLE": "العنوان",
        "TEXT": "النص",
        "STATUS": "الحالة",
        "REJECTED": "مرفوض",
        "ACCEPTED": "مقبول",
        "NEXT_BUTTON": "التالي",
        "PREVIOUS_BUTTON": "السابق",
        "ROWS_PER_PAGE_TEXT": "العدد في الصفحة",
        "NO_DATA_TEXT": "لا توجد بيانات للعرض",
        "PLACEHOLDER_SEARCH": "بحث",
        "MORE_INFO_ABOUT_ITEM": "مزيد من المعلومات حول {name}"
    },
    "MENU_ITEMS": {
        "TEXT_INPUT": "النص",
        "SELECT_USER_INFO": "اختيار معلومات المستخدم"
    },
    "TABLE_CONTROLS": {
        "COUNT": "العدد",
        "SEARCH": "بحث"
    },
    "FORM_LABELS": {
        "DEFAULT_GROUP_NAME": "اسم المجموعة الافتراضي",
        "PARENT_CATEGORY": "الفئة الوالدة",
        "HISTORY_TITLE": "عنوان التاريخ",
        "STEP": "الخطوة",
        "LAST_CALL_TIME": "وقت آخر مكالمة",
        "NEGOTIATIONS": "المناقشات التي تمت",
        "REMINDER_TIME": "وقت التذكير",
        "FOLLOW_UP_ITEMS": "بنود المتابعة في المكالمة التالية",
        "GROUP_NAME": "اسم المجموعة",
        "SEARCH": "بحث",
        "TITLE": "العنوان",
        "SEARCH_IN_TITLE": "بحث في العنوان",
        "FROM": "من",
        "TO": "إلى",
        "BIRTHDAY_FROM": "تاريخ الميلاد من",
        "BIRTHDAY_TO": "إلى تاريخ",
        "COUNT": "العدد",
        "ADD_PHONE_NUMBER": "إضافة رقم هاتف"
    },
    "TOAST": {
        "DEFAULT_GROUP_SUCCESS": "تمت إضافة المجموعة الافتراضية بنجاح.",
        "DEFAULT_GROUP_ERROR": "خطأ في إضافة المجموعة الافتراضية!",
        "ADD_HISTORY_ERROR": "خطأ في إضافة تاريخ العميل!",
        "DUPLICATE_NAME": "الاسم مكرر",
        "TAG_ADDED_SUCCESS": "تمت إضافة العلامة بنجاح.",
        "TAG_DELETED_SUCCESS": "تم حذف العلامة بنجاح",
        "TAG_EDITED_SUCCESS": "تم تعديل العلامة بنجاح",
        "GROUPS_ADDED_SUCCESS": "تمت إضافة المجموعات المختارة بنجاح.",
        "ADD_GROUP_ERROR": "خطأ في إضافة المجموعة الافتراضية!",
        "PHONE_COPIED_SUCCESS": "تم نسخ رقم الهاتف المحمول.",
        "SUCCESSFULLY_DELETED": "تم الحذف بنجاح",
        "ERROR_DELETING_CONTACT_FROM_PHONEBOOK": "خطأ في حذف جهة الاتصال من دفتر الهاتف!",
        "SHARE_SUCCESS": "تمت مشاركة دفتر الهاتف بنجاح.",
        "SHARE_ERROR": "خطأ في مشاركة دفتر الهاتف!",
        "NUMBER_ALREADY_ADDED": "الرقم موجود مسبقاً!",
        "CHANGES_SAVED_SUCCESS": "تم حفظ التغييرات بنجاح.",
        "CHANGES_SAVE_ERROR": "خطأ في حفظ التغييرات!"
    },
    "HEADERS": {
        "GRADUAL_SEND": "الإرسال التدريجي",
        "GRADUAL_SEND_HINT": "(للإرسال بأعداد أكبر من ٥٠٠ رقم)"
    },
    "CHECKBOX_LABELS": {
        "GRADUAL_SENDING": "الإرسال بشكل تدريجي",
        "DELETE": "حذف",
        "EDIT": "تعديل",
        "ADD": "إضافة"
    },
    "MESSAGES": {
        "SENDING_INTERVAL_QUESTION": "بعد كل {time} رسالة، هل يجب إرسال الرسائل النصية؟"
    },
    "LABELS": {
        "TIME_INTERVAL": "الفاصل الزمني",
        "MESSAGE_COUNT": "عدد الرسائل"
    },
    "TIME_TYPES": {
        MINUTE: "دقيقة",
        HOUR: "ساعة",
        DAY: "يوم",
        WEEK: "أسبوع",
        SECOND: "ثانية"
    },
    "HINTS": {
        "MESSAGE_COUNT_PER_PART": "أدخل عدد الرسائل في كل جزء من الإرسال."
    },
    "RULES": {
        "MESSAGE_COUNT_MIN_LIMIT": "عدد الرسائل في كل جزء لا يمكن أن يكون أقل من ٥٠٠!"
    },
    "TABLE_HEADERS": {
        "ROW": "الرقم",
        "TITLE": "العنوان",
        "STEP": "الخطوة",
        "REMINDER_TIME": "وقت التذكير",
        "LAST_CALL_TIME": "وقت آخر مكالمة",
        "RECORDER": "المسجل",
        "MANAGEMENT": "الإدارة",
        "ID": "المعرّف",
        "GROUP_NAME": "اسم المجموعة",
        "PARENT": "الوالد",
        "CREATED_AT": "تم الإنشاء",
        "IMAGE": "صورة",
        "FULL_NAME": "الاسم الكامل",
        "EMAIL": "البريد الإلكتروني",
        "PHONE_NUMBER": "رقم الهاتف المحمول",
        "JOB_COMPANY": "المسمى الوظيفي والشركة",
        "CREATION_TIME": "وقت الإنشاء",
        "PHONEBOOK": "دفتر الهاتف",
        "ACTIONS": "العمليات",
        "USER": "المستخدم"
    },
    "PROPS": {
        "SOURCE_NUMBER_LABEL": "الرقم المصدر"
    },
    "MODAL": {
        "INFO_TITLE": "تنبيه.",
        "INFO_MESSAGE_NEWS_NUMBER": "عند إرسال الرسائل النصية القصيرة برقم \"{number}\"، يجب أن يكون الحد الأدنى للعدد هو ١٠٠٠.",
        "CONFIRM_DELETE_GROUP": "تأكيد حذف المجموعة؟"
    },
    "SPECIAL_NUMBERS": {
        "NEWS_SEND": "إرسال إخباري"
    },
    "POPUP_TITLES": {
        "SELECT_GROUP": "اختيار مجموعة",
        "CREATE_NEW_GROUP": "إنشاء مجموعة جديدة",
        "SELECT_GROUP_SUBGROUP": "اختيار المجموعة والمجموعة الفرعية",
        "CREATE_DEFAULT_GROUP": "إنشاء مجموعة افتراضية",
        "DELETE_CONTACT_FROM_GROUP": "حذف جهة الاتصال من المجموعة",
        "DELETE_CONTACT": "حذف جهة الاتصال",
        "SHARE_PHONEBOOK": "مشاركة دفتر الهاتف",
        SYSTEM_GUIDE: "دليل نظام محطة الإعلانات"
    },
    "CARD_TITLES": {
        "ENTER_GROUP_NAME": "أدخل الاسم الذي تريده للمجموعة",
        "SELECT_PERMISSIONS": "اختيار الوصول لدفتر الهاتف {name}:",
        "PEOPLE_WITH_ACCESS": "الأشخاص الذين لديهم وصول"
    },
    "LOADING_MESSAGES": {
        "FETCHING_CATEGORIES": "جاري تحميل الفئات..."
    },
    "RADIO_LABELS": {
        "GROUP_WITH_SUBGROUPS": "إضافة المجموعة مع المجموعات الفرعية",
        "SELECTED_GROUP_ONLY": "إضافة المجموعة المختارة فقط",
        "DELETE_FROM_THIS_GROUP_ONLY": "حذف جهة الاتصال من هذه المجموعة فقط",
        "DELETE_FROM_ALL_GROUPS": "حذف جهة الاتصال من جميع المجموعات"
    },
    "FILTER_LABELS": {
        "ADDRESS": "العنوان",
        "EMAIL": "البريد الإلكتروني",
        "WEBSITE": "موقع الويب",
        "CUSTOM_FIELD": "حقل مخصص",
        "DATE": "التاريخ"
    },
    "CARD_SUBTITLES": {
        "SHARE_INSTRUCTION": "باختيار أي من الخيارات التالية، قم بمشاركة الوصول المطلوب مع الآخرين."
    },
    "VALIDATION": {
        "INVALID_PHONE_NUMBER": "الرجاء إدخال رقم هاتف صحيح"
    },
    "LIST_ITEM_TITLES": {
        "DELETE": "حذف",
        "EDIT": "تعديل",
        "ADD": "إضافة",
        "REMOVE_ACCESS": "إزالة الوصول"
    },
    CAMPAIGN: {
        CAMPAIGN_NAME: "اسم الحملة",
        TEXT: "النص",
        MESSAGE: "الرسالة",
        FOR: "لأجل",
        SELECT_CAMPAIGN: "اختيار حملة",
        CLICK_ROW: "اضغط على الصف المطلوب.",
        NEW: "جديد",
        SUBMIT_CAMPAIGN: "تسجيل حملة",
        TIME: "الساعة",
        MESSAGE_COUNT: "عدد الرسائل",
        PAGE_COUNT: "إجمالي الرسائل (صفحة)",
        PAGE: "صفحة",
        CANCEL_TEXT: "إلغاء11",
        TRACKABLE_LINK: "رابط قابل للتتبع",
        WARNING_TEXT: "الرجاء تصحيح نص/نصوص حملتك المختارة!",
        WARNING_TITLE: "الرجاء تصحيح عنوان/عناوين حملتك المختارة!",
        WARNING_GAP: "الرجاء تصحيح الفاصل/الفواصل الزمنية لحملتك المختارة!",
        WARNING_OPERATOR: "الرجاء تصحيح المشغل/المشغلين لحملتك المختارة!",
        MAX_ITEMS_ERROR: "يمكن إضافة 10 عناصر كحد أقصى."
    },
    ADS: {
        LIVE_SMS: "إرسال رسائل نصية قصيرة مباشرة",
        BUY_JOB_DB: "شراء قاعدة بيانات الوظائف",
        SMART_LADDER: "سُلم ذكي لإعلانات ديفار",
        JOB_SMS: "إرسال رسائل نصية قصيرة للوظائف",
        WEB_DESIGN: "طلب تصميم موقع ويب",
        SEO: "طلب سيو الموقع",
        MAP_SMS: "إرسال رسائل نصية قصيرة من الخريطة",
        GRADUAL_LADDER: "سُلم تدريجي لإعلانات ديفار",
        SEO_ALT: "طلب سيو الموقع",
        SITE_SUPPORT: "إدارة ودعم الموقع",
        CITY_SMS: "إرسال رسائل نصية قصيرة للمدينة والمحافظة",
        AUTO_CHAT: "دردشة آلية ديفار"
    },
    TUTORIALS: {
        WHATSAPP_SUPPORT: "الدعم عبر واتساب",
        TICKET_SUPPORT: "تسجيل تذكرة"
    },
    INCREASE: {
        PAN: "رقم البطاقة",
        CVV2: "CVV2",
        MONTH: "الشهر",
        YEAR: "السنة",
        PIN2: "الرمز الثاني",
        GET_OTP: "احصل على الرمز الثاني",
        PAY: "ادفع",
        INVALID_PAN: "رقم البطاقة غير صحيح",
        INVALID_CVV2: "رمز CVV2 غير صحيح"
    },
    WALLET: {
        CustomCharge: "شحن المحفظة",
        withdrawTitle: "سحب من المحفظة",
        transactionListTooltip: "قائمة معاملاتك",
        reloadTooltip: "إعادة تحميل",
        withdrawTooltip: "سحب من المحفظة",
        AmountLabel: "الرصيد ",
        SelectAmount: "اختيار المبلغ",
        Amount: "المبلغ",
        Currency: "ريال",
        GateWay: "بوابة الدفع",
        noGateWay: "لم يتم العثور على بوابة دفع",
        Pay: "ادفع",
        PriceNotInRange: "يجب أن يكون المبلغ بين {min} و {max}.",
        ErrorOnRedirectToGateWay: "خطأ في التحويل إلى بوابة الدفع",
        ErrorGeneral: "خطأ",
        MinAmountError: "المبلغ الذي أدخلته أقل من الحد الأدنى المسموح به.",
        MinBazarAmountError: "المبلغ لا يمكن أن يكون أقل من ١٠ آلاف ريال!",
        BazarSuccessInfo: "في حالة الدفع بنجاح، سيتم شحن محفظتك في غضون دقيقة إلى 3 دقائق.",
        withdrawableBalance: "الرصيد القابل للسحب",
        withdrawFee: "رسوم السحب من الحساب: ٥٠,٠٠٠ ريال!",
        selectAccount: "اختيار حساب",
        addAccount: "إضافة حساب",
        submitWithdraw: "تسجيل سحب",
        accountRequiredInfo: "جميع المعلومات مطلوبة.",
        ownerName: "اسم صاحب الحساب",
        ownerLastName: "اسم العائلة",
        bankName: "اسم البنك",
        accountNumber: "رقم الحساب",
        cardNumber: "رقم البطاقة",
        sheba: "رقم الشيبا",
        onlyPersian: "مسموح بإدخال الحروف العربية فقط!",
        cardNumberLength: "يجب أن يكون عدد أرقام البطاقة ١٦ رقماً!",
        shebaLength: "يجب أن يكون عدد أرقام الشيبا ٢٤ رقماً!",
    },
    USER_PICKER: {
        SELECT_USER: "اختيار المستخدم",
        SELECT_USERS: "اختيار المستخدمين",
        SEARCH: "بحث",
        PERSON: "شخص طبيعي",
        COMPANY: "شخص اعتباري",
        ID: "المعرّف",
        NAME: "الاسم",
        LASTNAME: "اسم العائلة",
        USERNAME: "اسم المستخدم",
        PHONE: "رقم الهاتف المحمول",
        TYPE: "نوع المستخدم"
    },
    NEWS: {
        TITLE: "أخبار پیامک لند",
        VIEW_BUTTON: "عرض",
        NO_NEWS: "لا توجد أخبار جديدة.",
        FETCH_ERROR: "فشل في جلب الأخبار!"
    },
    MENUS: {
        //qr
        QR_TOOL: "أداة QR",
        CREATE_DYNAMIC_QR: "إنشاء QR ديناميكي",
        QR_MANAGEMENT: "إدارة QR",
        QR_MONITORING: "مراقبة QR",
        MY_QR_LIST: "قائمة QR الخاصة بي",
        PHYSICAL_NFC_ORDERS: "طلبات بطاقة NFC والبطاقات المادية",
        BULK_QR_GENERATION: "إنشاء رمز QR بالجملة",
        IMAGE_CREATION_TOKEN: "رمز إنشاء الصورة",
        CATEGORIES: "فئات",
        CREATE_DEFAULT_PRODUCT: "إنشاء منتج افتراضي",
        DOMAINS: "النطاقات",
        REMINDERS: "تذكيرات",
        AUTOMATIC_CREATION: "إنشاء تلقائي",
        SEND_ADMIN_SMS: "إرسال رسالة نصية قصيرة للمسؤول",
        UNCREATED_CARDS: "بطاقات غير منشأة",
        MODELS_LIST: "قائمة النماذج",
        UPLOAD_CENTER: "مركز التحميل",
        INFORMATION_REGISTRATION: "تسجيل المعلومات",
        TARIFFS: "التعريفات",
        REGISTERED_INFO_LIST: "قائمة المعلومات المسجلة",
        //core
        "personel": "الموظفون",
        "workReports/create": "تقرير العمل",
        "admin/user-guide": "دليل المستخدم",
        "phonebook": "نادي العملاء",
        "contact/list": "اتصال يار (شكرًا على الاتصال)",
        "admin/transferRequests": "طلبات السحب",
        "admin/wallet": "المحفظة الجديدة",
        "admin/cdr": "مراقبة المكالمات",
        "admin/campaign": "الحملة",
        "admin/message-categories": "تصنيفات الرسائل",
        "admin/customers": "إدارة علاقات العملاء",
        "admin/notifications": "إشعارات المدير",
        "admin/user-history/notifications": "إشعارات سجل المستخدمين",
        "admin/messages": "الرسائل",
        "profile": "الملف الشخصي",
        "admin/workReports": "إدارة تقارير العمل",
        "panel": "شراء الباقة",
        "adminDiscounts": "الخصومات",
        "departments": "الأقسام",
        "adminTickets": "إدارة التذاكر",
        "admin/configs": "الإعدادات",
        "notifications": "الإشعارات",
        "user/confirmed": "طلبات المستخدمين",
        "users": "قائمة المستخدمين",
        "payments": "بوابة الدفع",
        "permission": "الصلاحيات",
        "panels": "الباقات",
        "category": "القوائم",
        "content": "المحتوى",
        "role": "الأدوار",
        "core/admin": "إدارة النواة"
    }
}
